// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyb6Ocj0-w2INw_4SxsPFqy_XoFm5VJqo',
    appId: '1:347823340663:web:cc8f08971d389a00899a72',
    messagingSenderId: '347823340663',
    projectId: 'krainet-test',
    authDomain: 'krainet-test.firebaseapp.com',
    storageBucket: 'krainet-test.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjFivBnld_2rBrHgMqj0yQCbbYNkW8aiI',
    appId: '1:347823340663:android:0dc0ba107694ba08899a72',
    messagingSenderId: '347823340663',
    projectId: 'krainet-test',
    storageBucket: 'krainet-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOeutmyf4u6VVCyU_ABZfw-GlL-Hdf9po',
    appId: '1:347823340663:ios:b7e20c29efb26a5f899a72',
    messagingSenderId: '347823340663',
    projectId: 'krainet-test',
    storageBucket: 'krainet-test.firebasestorage.app',
    iosBundleId: 'com.example.krainetTest',
  );
}
